FROM grapesjs-base:latest

RUN yarn add -W \
    react@^19.0.0 \
    react-dom@^19.0.0 \
    @types/react@^19.0.0 \
    @types/react-dom@^19.0.0

WORKDIR /app/packages/grapesjs-react
RUN yarn link

WORKDIR /app/packages/grapesjs-react-app-19-simple
RUN yarn link @grapesjs/react

WORKDIR /app
RUN yarn install

WORKDIR /app/packages/grapesjs-react-app-19-simple

EXPOSE 5173

CMD ["yarn", "dev", "--host", "0.0.0.0"]