FROM mcr.microsoft.com/playwright:v1.40.0-jammy

WORKDIR /app

COPY package.json yarn.lock ./
COPY tests/package.json ./tests/package.json

RUN yarn install

WORKDIR /app/tests
RUN yarn add @playwright/test@1.40.1

COPY tests/src ./src
COPY tests/playwright.config.ts ./playwright.config.ts

ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
ENV PWTEST_SKIP_TEST_OUTPUT=1

CMD ["yarn", "playwright", "test"]