name: Setup Project
description: Sets up the project by installing dependencies

inputs:
  node-version:
    required: false
    default: 22.4.1
    description: "The version of Node.js to use."

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"
        cache: "yarn"
    - name: Install dependencies
      run: yarn
      shell: bash

    - name: Install React Dependencies in Root
      shell: bash
      run: |
        cd ./packages/grapesjs-react && yarn add \
        react@^19.0.0 \
        react-dom@^19.0.0 \
        @types/react@^19.0.0 \
        @types/react-dom@^19.0.0
