name: Quailty Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  quailty:
    runs-on: ubuntu-latest

    name: Check Formatting and Linting
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Project Base
        uses: ./.github/actions/setup-project

      - name: Lint Checks
        uses: ./.github/actions/lint
