name: Publish GrapesJS React latest
on:
  push:
    branches: [dev]

jobs:
  publish:
    if: "contains(github.event.head_commit.message, 'Release GrapesJS React latest:')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Build
        run: yarn build:core
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> ./packages/grapesjs-react/.npmrc
          yarn publish:core:latest
